WIP: feat!: use strictly incrementing nonce to determine job relay order
InfinityVM/InfinityVM pull request #426
Opened 2024-12-24 21:27 UTC by emostov

2024-12-29 02:47 UTC, emostov commented on crates/coproc/src/job_executor.rs
> +        executor_rx: Receiver<ExecutorMsg>,
Renamed for consistency with the other channel sender/receivers

2024-12-29 02:52 UTC, emostov commented on crates/coproc/src/relayer.rs
> +            // missing
Couldn't figure this one out. Using `try_recv` seems ok for now but lmk if anyone has suggestions

2024-12-29 02:53 UTC, emostov commented on crates/coproc/src/relayer.rs
> +                // RelayMsg::Exit => return Ok(()),
```suggestion
```

2024-12-29 02:54 UTC, emostov commented on examples/clob/node/src/batcher.rs
> +        let (state_borsh, requests_borsh) = tokio::task::spawn_blocking(move || {
I was debugging some issues that I thought might be caused by the clob blocking. I left these changes since we should be doing sync DB IO in spawn blocking anyways

2024-12-29 02:55 UTC, emostov commented on examples/clob/node/src/engine.rs
> +        tokio::task::spawn_blocking(move || {
Same as with the matching game, this sync DB IO should be in a blocking thread

2024-12-29 03:20 UTC, emostov commented on crates/coproc/src/relayer.rs
> +            // missing
I haven't tried using a channel lib either, but thought it would be nice to stay consistent with flume everywhere altho not critical

2024-12-29 04:29 UTC, Avi-D-coder commented on crates/coproc/src/relayer.rs
> +            // missing
Why do we need a mpmc (flume) queue instead of a mpsc (tokio)?

2024-12-29 05:11 UTC, Avi-D-coder commented on crates/coproc/src/relayer.rs
> +            // missing
Using flume in async code can be a bit tricky.
cancel safety: https://github.com/zesterer/flume/issues/104 (note a linked bug https://github.com/n0-computer/iroh/pull/2536)
Perf https://github.com/zesterer/flume/issues/152

2024-12-29 05:14 UTC, Avi-D-coder commented on crates/coproc/src/execute.rs
> +                new_job = self.rx.recv_async() => {
Flume does not seem to be cancel safe and cannot be used with select (not sure about using it as async in general). See my other comment and this issue someone had:
https://github.com/n0-computer/iroh/issues/2415#issuecomment-2289069405

2024-12-29 16:08 UTC, emostov commented on crates/coproc/src/execute.rs
> +                new_job = self.rx.recv_async() => {
Oh great to know

2024-12-29 17:37 UTC, emostov commented on crates/coproc/src/relayer.rs
> +            // missing
I remove all the flume usage in this PR here: https://github.com/InfinityVM/InfinityVM/pull/426/commits/b9bf54076cd3ec00f7eca018ba67a11e68f96b37. However, still having issues with using `recv` (you can see the tests fail in the linked commit). When I go back to `try_recv`, things work again: https://github.com/InfinityVM/InfinityVM/pull/426/commits/418692c1e5f621a595ba1ee3f067855661e381da

2024-12-29 18:30 UTC, emostov commented
I update the DB writer service to use mpsc channel instead of flume: [5e86aab](https://github.com/InfinityVM/InfinityVM/pull/426/commits/5e86aab5d315d48bc1830c8eaffc175852a43692)

2024-12-29 19:43 UTC, Avi-D-coder requested changes

2024-12-29 19:43 UTC, Avi-D-coder commented on crates/coproc/src/execute.rs
> +                            break
This None means we have no more messages coming into the actor, we likely still have jobs in progress.
We don't want to shutdown the actor here because it will lose the jobs in progress.
We only should shutdown when all jobs are relayed and this queue is droped and empty.

2024-12-30 01:35 UTC, MaanavKhaitan reviewed
Added a few comments

2024-12-30 01:35 UTC, MaanavKhaitan commented on crates/coproc/src/execute.rs
> +                                // This is not the next job to relay, so just store it for later
I'm curious, what's the reason we wanna have this `completed_tasks` tracking here in the executor? doesn't the queue in the relay basically guarantee this already?

2024-12-30 01:35 UTC, MaanavKhaitan commented on crates/coproc/src/intake.rs
> +        let execution_tx = if !self.active_actors.contains_key(&consumer_address) {
so if the CN goes down, the GTX server would need to re-submit jobs to the CN that weren't able to be relayed?

2024-12-30 01:35 UTC, MaanavKhaitan commented on Makefile
> +	cp contracts/out/Consumer.sol/Consumer.json crates/contracts/json
I was thinking about whether we need to modify the `JobManager` contract to enforce strictly incrementing nonce. Lmk if you disagree:

For stateful jobs, we don't need to enforce this because this is implicit through the state hash check

For stateless jobs, we don't need to enforce this because it doesn't matter what order the results are relayed in? Is there an example of a stateless job which would require results to be posted in order? I'm guessing that even if it is we don't need to enforce it at the protocol-level and can enforce it an individual Consumer-level

2024-12-30 07:09 UTC, Avi-D-coder commented on crates/coproc/src/execute.rs
> +                                // This is not the next job to relay, so just store it for later
The queue to the relayer does not order the tasks.
The executor actors does. The relayer actor could and maybe should be replaced with spawn tokio task, it's stateless.

2024-12-30 07:26 UTC, MaanavKhaitan commented on crates/coproc/src/execute.rs
> +                                // This is not the next job to relay, so just store it for later
ah I see, makes sense

2024-12-30 21:19 UTC, emostov commented on crates/coproc/src/relayer.rs
> +                    let fut = Self::relay_job_result(
Future, will update it

2024-12-30 21:24 UTC, emostov commented on crates/coproc/src/intake.rs
> +    /// Caution: this assumes the consumer address has already been validated to be exactly 20
The gRPC `submit_job` endpoint does this right now. The other user is the events listener and that is trusted code.

2024-12-30 21:26 UTC, emostov commented on crates/coproc/src/relayer.rs
We have 3 seperate things in this file: the relay chain client (JobRelayer), the actor (RelayActor), and the dlq relayer (RelayRetry). So wanted to keep the name general

2024-12-30 21:29 UTC, emostov commented on crates/coproc/src/intake.rs
> +        let execution_tx = if !self.active_actors.contains_key(&consumer_address) {
Yes. We can implement some extra logic in the CN to do this, but ultimately GTX needs to be in charge

2024-12-30 21:31 UTC, emostov commented on Makefile
> +	cp contracts/out/Consumer.sol/Consumer.json crates/contracts/json
Yup, I agree. The only reason to add it for GTX is just to give stronger guarantees that jobs will get rejected if they don't follow ordering, but its not a safety thing

2024-12-30 21:39 UTC, emostov commented on crates/coproc/src/execute.rs
> +                            break
I was going based off this sentence in the docs: https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Receiver.html#method.recv. 

> This method returns None if the channel has been closed and there are no remaining messages in the channel’s buffer. This indicates that no further values can ever be received from this Receiver. The channel is closed when all senders have been dropped, or when [close](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Receiver.html#method.close) is called.

In the context of the coproc, the current logic will never drop the sender so it should never return `None`. That being said, I think your initial logic of only exiting once the join set is empty is more future proof for refactors

2024-12-30 22:02 UTC, emostov commented on crates/coproc/src/execute.rs
> +                            break
Fixed here: [619f5d2](https://github.com/InfinityVM/InfinityVM/pull/426/commits/619f5d2c96e42ad090be1810932f5704ea755168)

2024-12-30 22:03 UTC, emostov commented on crates/coproc/src/relayer.rs
> +                    let fut = Self::relay_job_result(
[619f5d2](https://github.com/InfinityVM/InfinityVM/pull/426/commits/619f5d2c96e42ad090be1810932f5704ea755168)

2024-12-30 22:04 UTC, emostov commented on crates/coproc/src/execute.rs
> +                                // This is not the next job to relay, so just store it for later
The main case I think the relay actor might be helpful is when we need to retry submitting a job: if we just spawned new tasks we wouldn't be able to ensure that the eth nonce in the retried transactions is correct

2024-12-31 03:37 UTC, MaanavKhaitan commented on crates/coproc/src/relayer.rs
ah cool makes sense

2024-12-31 03:37 UTC, MaanavKhaitan commented on crates/coproc/src/intake.rs
> +        let execution_tx = if !self.active_actors.contains_key(&consumer_address) {
sounds good

2024-12-31 03:37 UTC, MaanavKhaitan commented on Makefile
> +	cp contracts/out/Consumer.sol/Consumer.json crates/contracts/json
sounds good, I think we can leave this for now then

2024-12-31 17:56 UTC, lucasege reviewed
left some comments

2024-12-31 17:56 UTC, lucasege commented on crates/coproc/src/relayer.rs
> +            // missing
how would you like to handle this for this PR? is this worth others taking a look to try to resolve or should we just merge as is?

2024-12-31 18:00 UTC, lucasege commented on crates/coproc/src/execute.rs
> +                                // This is not the next job to relay, so just store it for later
yeah i think it makes sense to keep as a service since it's fairly minimal right now.

2024-12-31 19:59 UTC, emostov commented on crates/coproc/src/relayer.rs
> +            // missing
Will try and find some time to debug `recv` this week, but will merge with `try_recv` if I can't

2025-01-01 02:07 UTC, Avi-D-coder approved these changes

2025-01-02 20:01 UTC, emostov commented
Made an issue for the `recv` bug in the relayer channel: https://github.com/InfinityVM/InfinityVM/issues. 

Planning on merging once CI passes

2025-01-02 20:05 UTC, merged